import { TRoom } from "./TablePage";

export const roomData: TRoom[] = [
  {
    id: "RM-001",
    building: "House-1",
    buildingCode: "ADM-01",
    floor: "Level-1",
    RoomNo: "101",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-02-15",
    createdBy: "John Doe",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-2",
        RoomNo: "201-1",
        roomStatus: "Inactive",
        roomZone: "3",
      },
    ],
  },
  {
    id: "RM-002",
    building: "House-1",
    buildingCode: "ADM-01",
    floor: "Level-1",
    RoomNo: "102",
    status: "Active",
    roomZone: "3",
    addedDate: "2026-02-15",
    createdBy: "John Doe",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "102-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-3",
        RoomNo: "301-1",
        roomStatus: "Active",
        roomZone: "1",
      },
    ],
  },
  {
    id: "RM-003",
    building: "House-1",
    buildingCode: "ADM-01",
    floor: "Level-2",
    RoomNo: "201",
    status: "Active",
    roomZone: "5",
    addedDate: "2026-02-15",
    createdBy: "John Doe",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "201-1",
        roomStatus: "Active",
        roomZone: "3",
      },
    ],
  },
  {
    id: "RM-004",
    building: "House-2",
    buildingCode: "PRD-A1",
    floor: "Level-1",
    RoomNo: "A-101",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-02-18",
    createdBy: "Sarah Ahmed",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "A-101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-2",
        RoomNo: "A-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-005",
    building: "House-2",
    buildingCode: "PRD-A1",
    floor: "Level-1",
    RoomNo: "A-102",
    status: "Inactive",
    roomZone: "3",
    addedDate: "2026-02-18",
    createdBy: "Sarah Ahmed",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "A-102-1",
        roomStatus: "Inactive",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-006",
    building: "House-2",
    buildingCode: "PRD-A1",
    floor: "Level-2",
    RoomNo: "A-201",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-02-18",
    createdBy: "Sarah Ahmed",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "A-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-3",
        RoomNo: "A-301-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-007",
    building: "House-3",
    buildingCode: "WRH-01",
    floor: "Level-1",
    RoomNo: "W-101",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-02-20",
    createdBy: "Michael Brown",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "W-101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-2",
        RoomNo: "W-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-008",
    building: "House-3",
    buildingCode: "WRH-01",
    floor: "Level-1",
    RoomNo: "W-102",
    status: "Active",
    roomZone: "3",
    addedDate: "2026-02-20",
    createdBy: "Michael Brown",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "W-102-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-009",
    building: "House-3",
    buildingCode: "WRH-01",
    floor: "Level-2",
    RoomNo: "W-201",
    status: "Inactive",
    roomZone: "4",
    addedDate: "2026-02-20",
    createdBy: "Michael Brown",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "W-201-1",
        roomStatus: "Inactive",
        roomZone: "2",
      },
      {
        roomFloor: "Level-4",
        RoomNo: "W-401-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-010",
    building: "House-4",
    buildingCode: "RND-01",
    floor: "Level-1",
    RoomNo: "R&D-101",
    status: "Active",
    roomZone: "5",
    addedDate: "2026-02-22",
    createdBy: "Emily Watson",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "R&D-101-1",
        roomStatus: "Active",
        roomZone: "3",
      },
      {
        roomFloor: "Level-2",
        RoomNo: "R&D-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-011",
    building: "House-4",
    buildingCode: "RND-01",
    floor: "Level-2",
    RoomNo: "R&D-201",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-02-22",
    createdBy: "Emily Watson",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "R&D-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-012",
    building: "House-2",
    buildingCode: "QCL-01",
    floor: "Level-1",
    RoomNo: "QC-101",
    status: "Active",
    roomZone: "3",
    addedDate: "2026-02-25",
    createdBy: "Robert Chen",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "QC-101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-3",
        RoomNo: "QC-301-1",
        roomStatus: "Active",
        roomZone: "1",
      },
    ],
  },
  {
    id: "RM-013",
    building: "House-1",
    buildingCode: "EWB-01",
    floor: "Level-1",
    RoomNo: "EW-101",
    status: "Active",
    roomZone: "3",
    addedDate: "2026-02-27",
    createdBy: "Fatima Begum",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "EW-101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-014",
    building: "House-1",
    buildingCode: "EWB-01",
    floor: "Level-2",
    RoomNo: "EW-201",
    status: "Inactive",
    roomZone: "4",
    addedDate: "2026-02-27",
    createdBy: "Fatima Begum",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "EW-201-1",
        roomStatus: "Inactive",
        roomZone: "2",
      },
      {
        roomFloor: "Level-4",
        RoomNo: "EW-401-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-015",
    building: "House-3",
    buildingCode: "MTW-01",
    floor: "Level-1",
    RoomNo: "MW-101",
    status: "Active",
    roomZone: "3",
    addedDate: "2026-03-01",
    createdBy: "David Kumar",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "MW-101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-016",
    building: "House-4",
    buildingCode: "CSF-01",
    floor: "Level-1",
    RoomNo: "CS-101",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-03-03",
    createdBy: "James Wilson",
    roomInformation: [
      {
        roomFloor: "Level-1",
        RoomNo: "CS-101-1",
        roomStatus: "Active",
        roomZone: "2",
      },
      {
        roomFloor: "Level-2",
        RoomNo: "CS-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-017",
    building: "House-4",
    buildingCode: "CSF-01",
    floor: "Level-2",
    RoomNo: "CS-201",
    status: "Active",
    roomZone: "4",
    addedDate: "2026-03-03",
    createdBy: "James Wilson",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "CS-201-1",
        roomStatus: "Active",
        roomZone: "2",
      },
    ],
  },
  {
    id: "RM-018",
    building: "House-4",
    buildingCode: "CSF-01",
    floor: "Level-2",
    RoomNo: "CS-202",
    status: "Inactive",
    roomZone: "3",
    addedDate: "2026-03-03",
    createdBy: "James Wilson",
    roomInformation: [
      {
        roomFloor: "Level-2",
        RoomNo: "CS-202-1",
        roomStatus: "Inactive",
        roomZone: "2",
      },
      {
        roomFloor: "Level-3",
        RoomNo: "CS-301-1",
        roomStatus: "Active",
        roomZone: "1",
      },
    ],
  },
];
